sudo: required
language: c
before_install:
  - sudo apt-get install -y --force-yes flex bison git qemu-kvm

script:
  - set +x
  - cd $AKAROS_ROOT
  - cd $AKAROS_ROOT && make ARCH=x86 defconfig
  - cd $AKAROS_ROOT && make xcc-clean
  - cd $AKAROS_ROOT && make xcc-uninstall
  - cd $AKAROS_ROOT && travis_wait 50 make xcc-build
  - cd $AKAROS_ROOT && make userclean
  - cd $AKAROS_ROOT && make install-base-libs
  - cd $AKAROS_ROOT && make testclean utestclean
  - cd $AKAROS_ROOT && make apps-clean
  - cd $AKAROS_ROOT && make apps-install
  - cd $AKAROS_ROOT && make tests utest
  - cd $AKAROS_ROOT && make fill-kfs
  - cd $AKAROS_ROOT && make
  - echo "Build SUCCESS"

env:
  global:
  - ARCH=x86
  - AKAROS_ROOT=$TRAVIS_BUILD_DIR
  - AKAROS_TOOLCHAINS="$AKAROS_ROOT/install"
  - PATH=$AKAROS_TOOLCHAINS/x86_64-ucb-akaros-gcc/bin:$PATH
  - MAKE_JOBS=4

notifications:
  email:
    recipients:
      - akaros-travis@googlegroups.com
    on_success: never
    on_failure: always

# we cat for logs in the order they are created (toolchain, then apps), so that
# the most recent is the last one printed.  The most recent should be the one
# that caused the error
after_failure:
  - echo "Build FAILED, trying to dump logs"
  - cd $AKAROS_ROOT/tools/compilers/gcc-glibc/build_logs && cat `ls -t | head -1`
  - cd $AKAROS_ROOT/build_logs && cat `ls -t | head -1`
